# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
# Copyright (C) 2020 Northwestern University.
#
# Invenio App RDM is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
          python-version: [3.7]
          requirements-level: [pypi]
          db-service: [postgresql10]
          search-service: [elasticsearch7]
          include:
          - db-service: postgresql10
            DB_EXTRAS: "postgresql"
          - search-service: elasticsearch7
            SEARCH_EXTRAS: "elasticsearch7"
    env:
      DB: ${{ matrix.db-service }}
      SEARCH: ${{ matrix.search-service }}
      EXTRAS: tests,${{ matrix.SEARCH_EXTRAS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate dependencies
        run: python -m pip install --upgrade pip
      - name: Install
        run: |
          pip install pipenv-to-requirements
          pipenv_to_requirements
          cat requirements.txt
          pip install 
          docker --version
          docker-compose --version
      - name: Run tests
        run: |
          pip install docker-services-cli
          pip install pytest
          pip install pytest-invenio
          ./run-tests.sh